title: Chorgo Dev
description: > # this means to ignore newlines until "baseurl:"
  I'm Jan Theile, and iOS Developer, who tries to learn new stuff as much as possible.
  Blogging about it, helps me to process the learned bits.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
##site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jan Theile # add your name
author-img: jantheile.jpg # add your photo
about-author: I'm an iOS Developer, trying to learn new stuff every day and blog from time to time about it. # add description
twitter: TheChorgo # add your Twitter handle
linkedin: jantheile # add your Linkedin handle
email: jan.theile@chorgo.de # add your Email address

# Disqus
discus-identifier: chorgo # add your discus identifier

# Tracker
analytics: UA-110091161-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 12
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
